"""Repository layer: the persistence contract for the VFS and chunk index.

Two implementations:

* :class:`~app.db.memory.InMemoryRepository` — deterministic, dependency-free,
  used by the test suite.
* :class:`~app.db.postgres.PostgresRepository` — the real thing, over asyncpg.

The interface is deliberately narrow and **owner-scoped**: every read takes an
``owner_id`` and filters on it. Authorisation is therefore enforced by the query
itself rather than by a check performed after fetching, which is the pattern that
avoids IDOR regressions when a new endpoint is added later.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class Repository(Protocol):
    """Persistence operations required by the VFS, upload, and download services."""

    # --- users & keys ---------------------------------------------------
    async def create_user(
        self, *, email: str | None, password_hash: str | None,
        display_name: str, telegram_user_id: int | None = None,
        telegram_username: str | None = None,
    ) -> dict[str, Any]: ...

    async def get_user(self, user_id: str) -> dict[str, Any] | None: ...
    async def get_user_by_email(self, email: str) -> dict[str, Any] | None: ...
    async def get_user_by_telegram_id(self, telegram_user_id: int) -> dict[str, Any] | None: ...
    async def get_user_wrapped_dek(self, user_id: str) -> bytes | None: ...
    async def set_user_wrapped_dek(self, user_id: str, wrapped: bytes, version: int) -> None: ...
    async def update_password_hash(self, user_id: str, password_hash: str) -> None: ...

    # --- refresh tokens -------------------------------------------------
    async def store_refresh_token(
        self, *, token_hash: bytes, family_id: str, user_id: str,
        expires_at: Any, user_agent: str | None, ip: str | None,
    ) -> None: ...
    async def get_refresh_token(self, token_hash: bytes) -> dict[str, Any] | None: ...
    async def rotate_refresh_token(
        self, *, old_hash: bytes, new_hash: bytes, family_id: str, user_id: str,
        expires_at: Any, user_agent: str | None, ip: str | None,
    ) -> None: ...
    async def revoke_token_family(self, family_id: str) -> None: ...
    async def revoke_refresh_token(self, token_hash: bytes) -> None: ...

    # --- nodes ----------------------------------------------------------
    async def get_root_node(self, owner_id: str) -> dict[str, Any] | None: ...
    async def get_node(self, node_id: str, owner_id: str) -> dict[str, Any] | None: ...
    async def find_child_by_name(
        self, owner_id: str, parent_id: str | None, name: str
    ) -> dict[str, Any] | None: ...
    async def list_children(
        self, *, owner_id: str, parent_id: str, order: str,
        limit: int, offset: int, kind: str | None = None,
        include_trashed: bool = False,
    ) -> list[dict[str, Any]]: ...
    async def count_children(
        self, owner_id: str, parent_id: str, include_trashed: bool = False
    ) -> int: ...
    async def list_trashed_nodes(
        self, owner_id: str, *, limit: int, offset: int
    ) -> list[dict[str, Any]]: ...
    async def list_ancestors(self, node_id: str, owner_id: str) -> list[dict[str, Any]]: ...
    async def create_folder_node(
        self, *, owner_id: str, parent_id: str, name: str
    ) -> dict[str, Any]: ...
    async def create_file_node(
        self, *, owner_id: str, parent_id: str, name: str, size_bytes: int,
        mime_type: str | None, chunk_size: int, total_chunks: int,
        encryption_mode: str, upload_state: str,
    ) -> dict[str, Any]: ...
    async def rename_node(self, node_id: str, owner_id: str, name: str) -> dict[str, Any]: ...
    async def move_node(
        self, node_id: str, owner_id: str, new_parent_id: str
    ) -> dict[str, Any]: ...
    async def set_starred(self, node_id: str, owner_id: str, starred: bool) -> dict[str, Any]: ...
    async def trash_node(self, node_id: str, owner_id: str, purge_after_days: int) -> None: ...
    async def restore_node(self, node_id: str, owner_id: str) -> dict[str, Any]: ...
    async def delete_node(self, node_id: str, owner_id: str) -> None: ...
    async def is_descendant(self, node_id: str, candidate_ancestor_id: str) -> bool: ...
    async def copy_file_node(
        self, *, source_node_id: str, owner_id: str, parent_id: str, name: str
    ) -> dict[str, Any]: ...
    async def copy_folder_subtree(
        self, *, source_node_id: str, owner_id: str, parent_id: str, name: str
    ) -> dict[str, Any]: ...
    async def finalize_file_node(
        self, *, node_id: str, owner_id: str, sha256_hex: str | None, hash_mode: str
    ) -> dict[str, Any]: ...
    async def search_nodes(
        self, *, owner_id: str, query: str, mime: str | None, kind: str | None,
        include_trashed: bool, limit: int, offset: int,
    ) -> list[dict[str, Any]]: ...

    # --- quota ----------------------------------------------------------
    async def reserve_quota(self, owner_id: str, size_bytes: int) -> tuple[bool, int, int]: ...
    async def release_quota(self, owner_id: str, size_bytes: int) -> None: ...
    async def recompute_usage(self, owner_id: str) -> int: ...
    async def usage_breakdown(self, owner_id: str) -> dict[str, Any]: ...
    async def ping(self) -> bool: ...
    async def list_storage_pools(self) -> list[dict[str, Any]]: ...

    # --- chunks ---------------------------------------------------------
    async def insert_chunk(self, **kwargs: Any) -> dict[str, Any] | None: ...
    async def get_chunk(self, node_id: str, chunk_index: int) -> dict[str, Any] | None: ...
    async def list_chunks(self, node_id: str) -> list[dict[str, Any]]: ...
    async def list_chunks_in_range(
        self, *, node_id: str, first_index: int, last_index: int
    ) -> list[dict[str, Any]]: ...
    async def list_chunk_indices(self, node_id: str) -> list[int]: ...
    async def sum_chunk_plaintext_bytes(self, node_id: str) -> int: ...
    async def delete_node_chunks(self, node_id: str) -> None: ...
    async def list_chunk_replicas(self, chunk_id: str) -> list[dict[str, Any]]: ...
    async def record_chunk_read_failure(
        self, *, chunk_id: str, message_id: int, error: str
    ) -> None: ...

    # --- upload sessions ------------------------------------------------
    async def create_upload_session(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_upload_session(self, upload_id: str) -> dict[str, Any] | None: ...
    async def find_upload_by_idempotency(
        self, owner_id: str, key: str
    ) -> dict[str, Any] | None: ...
    async def bump_upload_progress(
        self, *, upload_id: str, plaintext_delta: int, ciphertext_delta: int
    ) -> None: ...
    async def complete_upload_session(self, *, upload_id: str) -> None: ...
    async def abort_upload_session(self, *, upload_id: str) -> None: ...

    # --- storage pools --------------------------------------------------
    async def choose_storage_pool(
        self, *, size_bytes: int, prefer_available: bool = True
    ) -> dict[str, Any]: ...
    async def register_storage_pool(
        self, *, label: str, telegram_channel_id: int, max_bytes: int = 0, weight: int = 100
    ) -> dict[str, Any]: ...

    # --- jobs -----------------------------------------------------------
    async def enqueue_job(self, kind: str, payload: dict[str, Any]) -> None: ...

    # --- audit ----------------------------------------------------------
    async def audit(
        self, *, actor_user_id: str | None, action: str, target_type: str | None = None,
        target_id: str | None = None, outcome: str = "success",
        detail: dict[str, Any] | None = None,
    ) -> None: ...